// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqvtrovbrjxbppdxnbfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxdnRyb3Zicmp4YnBwZHhuYmZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMDk5ODgsImV4cCI6MjA3MjY4NTk4OH0.7vSfmKAd38b8S857fF5d5Atu94B4NKYDRFS5Tfo7KQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});